config/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'sumda'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sumda.urls'))
]

sumda/urls.py
from django.urls import path, include
from .views import *
from . import views


app_name = 'sumda'

urlpatterns = [
    path('', main, name='main'),
    path('signup/',views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('detail/<int:pk>', views.detail, name="detail"),
    path('write', write, name='write'),
    

]

sumda/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    nickname = models.CharField(verbose_name='사용자 닉네임', max_length=50)


class Profile(models.Model):
    objects = models.Manager()
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)
    follower = models.ManyToManyField(
        User, related_name='follower', blank=True)
    following = models.ManyToManyField(
        User, related_name='following', blank=True)
    request = models.ManyToManyField(
        User, related_name='request', blank=True)


class Diary(models.Model):
    objects = models.Manager()
    nickname = models.CharField(max_length=50)
    profile = models.ForeignKey(
        Profile, related_name='profile', on_delete=models.CASCADE, blank=True, null=True)
    address = models.CharField(
        verbose_name='주소', max_length=100, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    title = models.CharField(verbose_name='일기 제목', max_length=100)
    content = models.TextField(blank=True, null=True)
    receiver = models.ForeignKey(
        Profile, related_name='receiver', on_delete=models.CASCADE, blank=True, null=True)
    block = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    objects = models.Manager()
    comment = models.TextField(blank=True, null=True)
    diary = models.ForeignKey(
        Diary, related_name='diary', on_delete=models.CASCADE, blank=True, null=True)
    nickname = models.CharField(max_length=50)

sumda/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User, Comment
#회원가입
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2','nickname']

#댓글
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['nickname', 'comment']

sumda/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from .forms import SignupForm, CommentForm
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.http import JsonResponse
from urllib.parse import urlparse

from .models import *


def main(request):
    posts = Diary.objects.all()
    return render(request, 'main.html',  {'posts_list':posts})

#상세보기 페이지 (댓글 폼)
def detail(request, pk):
    post = get_object_or_404(Diary, pk = pk)
    comment_list = Comment.objects.filter(diary=post)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.diary = post
            comment.save()
            return redirect('/detail/'+str(pk) )
    else :
        comment_form = CommentForm()
        
    return render(request, 'detail.html', {'post':post, 'comment_list':comment_list, 'comment_form':comment_form })
    

def send(request):
    recieved_diary = Diary.objects.filter(receiver=None)
    recieved_diary.receiver = request.user

# 로그인, 회원가입, 로그아웃 기능
def signup_view(request):
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            new_profile = Profile()
            new_profile.user = user
            new_profile.save()
            return redirect('/')
    else:
        form=SignupForm()
    return render(request, 'signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request=request, username=username, password=password) 
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})
def logout_view(request):
	logout(request)
	return redirect('/')



def write(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == 'GET':

        return render(request, 'write.html')
    elif request.method == 'POST':

        new_diary = Diary()
        new_diary.nickname = request.POST['nickname']
        new_diary.profile = profile
        new_diary.content = request.POST['content']
        new_diary.title = request.POST['title']
        if request.POST['location']:
            new_diary.address = request.POST['location']
        else:
            pass
        new_diary.save()
        return redirect('/')


@csrf_exempt
def location(request):
    req = json.loads(request.body)
    latitude = req['latitude']
    longitude = req['longitude']
    address = req['address']
    user = request.user
    profile = Profile.objects.get(user=user)
    return JsonResponse({'latitude': latitude, 'longitude': longitude, 'address': address})

sumda/templates/detail.html
<h1>{{ post.title }}</h1>

<p>{{post.content}}</p>
<hr>
<br><br><br><br><br>

<!-- 새 댓글을 입력하는 부분 -->
<form method='post'>
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">댓글 달기</button>
</form>

<!-- 기존 댓글을 보여주는 부분 -->
{% for c in comment_list %}
<p>{{ c.comment }}</p><hr>

{% endfor %}

sumda/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/53a8c415f1.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="static/css/signup.css">

</head>
<body>
    <nav class="navbar">
        
        <div class="navbar_logo">
            <a href="{% url 'sumda:main' %}">Sumda</a>
        </div>
        <hr>
    </nav>
    
    <form method="POST">
        <div class="wrap">
            <div class="login">
                <h2>Log-in</h2>
            

                <div class="login_id">
                    <h4>E-mail</h4>
                    <input type="email" name="" id="" placeholder="Email">
                </div>
                <div class="login_pw">
                    <h4>Password</h4>
                    <input type="password" name="" id="" placeholder="Password">
                </div>
                <div class="submit">
                    <button type="submit">submit</button>
                </div>
            

            </div>
        </div>
    </form>
</body>
</html>
<!--
<form method="POST">
    {% csrf_token %}
   
    <button type="submit">sum</button>
</form>-->

sumda/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="static/css/main.css" />
        <link rel="stylesheet" href="static/css/section.css" />
        <script src="static/css/main.js" defer></script>
        <script src="https://kit.fontawesome.com/2d323a629b.js" crossorigin="anonymous"></script>
        <!--아이콘 폰트어썸-->
        <title>Main</title>
    </head>
    <body>
        <nav class="navbar">
            <div class="navbar_logo">
                <a href="#">Sumda</a>
            </div>
            <div class="navbar_icons">
                <ul>
                    <li><a>Library</a></li>
                    <!--로그인 o-->
                    <li><a>Mypage</a></li>
                    <!--로그인 o-->
                    <li><i class="fab fa-instagram"></i></li>
                    <!--그냥 sns 연동-->
                    <li><i class="fas fa-pencil-alt"></i></li>
                    <!--새 일기 작성하기/ 로그인 하면 뜨게 설정-->
                </ul>
            </div>

            <a class="navbar_toggleBtn" href="{% url 'sumda:login' %}"><i class="fas fa-bars"></i></a>
        </nav>

        <section>
            <div class="section_text">
                <h1>당신에게 도착한 일기가 있습니다!</h1>
                <h1>일기를 열람할까요?</h1>
                <a class="open" href="{% url 'sumda:login' %}"><p>login</p></a>
            </div>
        </section>

        <!--중간 네브-->

        <div class="mid">
            <nav>
                <ul class="navbar_menu">
                    <li><a class="my">My</a></li>
                    <!--로그인 o-->
                    <li><a class="others">Others</a></li>
                    <!--로그인 o-->
                </ul>

                <div class="navbar_icons">
                    <ul>
                        <li><i class="fab fa-instagram"></i></li>
                        <!--그냥 sns 연동-->
                        <li><i class="fas fa-pencil-alt"></i></li>
                        <!--새 일기 작성하기/ 로그인 하면 뜨게 설정-->
                    </ul>
                </div>

                <a class="navbar_toggleBtn" href="#"><i class="fas fa-bars"></i></a>
            </nav>
        </div>

        <!--내 글 보이는 곳-->
        <main>
            <div class="big_box">
                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <a href=""><h4>조금은 고된 하루</h4></a>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>
            </div>
        </main>

        <main>
            <div class="big_box2">
                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <a href=""><h4>조금은 고된 하루</h4></a>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>

                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>
                <selction class="diary">
                    <div class="wrapper">
                        <img src="static/css/poster1.jpg" alt="" />
                        <div class="diary_header">
                            <h4>조금은 고된 하루</h4>
                            <!--제목넣기-->
                            <h5>Written on July 6th</h5>
                            <!--날짜넣기-->
                        </div>
                    </div>
                </selction>
            </div>
        </main>

        <footer>
            <ul>
                <li><i class="fas fa-book"></i></li>
                <li><p>Made by Sumda...</p></li>
                <li>2021 신촌 해커톤</li>
            </ul>
        </footer>
    </body>
</html>

sumda/templates/mypage.html
<h3>나에게 온 팔로우 요청</h3>
{% for req in requests %}
<p>{{req.nickname}}</p>
<a href="{% url 'sumda:accept' req.id%}"><button>수락</button></a>
<a href="{% url 'sumda:reject' req.id%}"><button>거절</button></a>
{% endfor %}
<h3>나의 팔로우 목록</h3>
{% for following in followings %}
<p>{{following.nickname}}</p>
{% endfor %}
<h3>내 팔로워</h3>
{% for follower in followers %}
<p>{{follower.nickname}}</p>
{% endfor %}

sumda/templates/others.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="main.css">
    
    <link rel="stylesheet" href="detail.css">
    <script src="main.js" defer></script>
    <script
    src="https://kit.fontawesome.com/2d323a629b.js"
    crossorigin="anonymous"
  ></script><!--아이콘 폰트어썸-->
    <title>Main</title>
</head>

<body>
    <nav class="navbar">
        
        <div class="navbar_logo">
            <i class="fas fa-book"></i>
            <a href="#">Sumda</a>

        </div>

        <ul class="navbar_menu">
            <li><a>Library</a></li><!--로그인 o-->
            <li><a>Mypage</a></li><!--로그인 o-->
            <li><a>Login</a></li><!--로그인 x-->
            <li><a>Signup</a></li><!--로그인 x-->
            <li><a>Logout</a></li><!--로그인 o-->
            <li><a>More</a></li>

        </ul>

        <div class="navbar_icons">
            <ul>
                <li><i class="fab fa-instagram"></i></li><!--그냥 sns 연동-->
                <li><i class="fas fa-pencil-alt"></i></li><!--새 일기 작성하기/ 로그인 하면 뜨게 설정-->
            </ul>

        </div>

        <a class="navbar_toggleBtn" href="#"><i class="fas fa-bars"></i></a>
    </nav>

    <!-- 일기 디테일 보기-->

    
    <selection class="diary">
        <div class="wrapper">

            <div class="diary_header">
              <h4>조금은 고된 하루</h4> <!--제목넣기-->
              <h5>Written on July 6th</h5> <!--날짜넣기-->
            </div>
          
            <img src="poster1.jpg" height="900px" width="400px"/>

            <div class="text_box">
            <h1>Text</h1>
            <p class="text"> 

                즐거운 학교에서 펴낸 <현대소설 너를 읽어주마> 34~51쪽까지 읽었다. 
                
                이 책의 첫 번째 단편인 양귀자의 <한계령>은 완독했다.
         
                마지막까지 읽었는데도 예전에 읽은 것이 전혀 기억나지 않고
                
                처음 읽는 듯한 마음이다.
                
                억지로 기억을 되살려보니
                
                전에는 아주 힘들게 읽었던 듯하다.
    
                그렇다면 이번에는?
                
                두 가지 면에서 흥미있었다.
         
                첫째, 작중 화자가 고향 친구의 전화를 받고 과거를 회상하는 장면은
                
                마치 나의 일인듯 공감이 갔고,
                
                둘째, 교과서에 나오는 <원미동 사람들>의 등장인물들을
                
                곳곳에서 확인하면서 반가움을 느꼈고,
                
                <원미동 사람들>의 배경을 보다 확실히 그릴 수 있었다.

                힘들었던 점은 마지막 장면이었다.
                
                작중화자가 결국은 옛친구를 찾아가서 
                
                찐빵집 딸 '박미화'에서 밤무대 무명가수 '미나박'을 확인할 
                
                그 때 작중화자가 느끼는 마음이 금새 마음에 와 닿지 않았다.
                두어 번 반복하여 읽고,
                
                책 옆의 주해(수험생을 위한 책이므로 주해가 잘 되어 있음)를 읽고서야
                
                어느 정도 이해는 갔다

                그래도 작가와 같은 정도로 몰입하지 못 한 것은
                
                이 책에서 소재 이상의 의미를 갖고 있는 두 노래,
                
                <검은 상처의 블루스>와 <한계령>에 대해
                
                내가 아는 바가 없기 때문이다.</p>
            </div>
            
            <hr>

            <class class="comment_box">

                <h1>Comment</h1>

                <p class="comment">오늘은 어쩌구 저쩌구 블라블라 ㅁㄴㄹㄴㄹㄴㅁㄹㄴㄹㄴㅁㄹㄴㄹ
                ㄴㅁㄹㄴㄹㄴㅁㄹ오늘은 어쩌구 저쩌구 블라블라 ㅁㄴㄹㄴㄹㄴㅁㄹㄴㄹㄴㅁㄹㄴㄹ
                ㄴㅁㄹㄴㄹㄴㅁㄹ오늘은 어쩌구 저쩌구 블라블라 ㅁㄴㄹㄴㄹㄴㅁㄹㄴㄹㄴㅁㄹㄴㄹ
                ㄴㅁㄹㄴㄹㄴㅁㄹ 
                
                오늘은 어쩌구 저쩌구 블라블라 ㅁㄴㄹㄴㄹㄴㅁㄹㄴㄹㄴㅁㄹㄴㄹ
                ㄴㅁㄹㄴㄹㄴㅁㄹ</p>

            </div>

           

        
        </div>

    


    </selection>

sumda/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/53a8c415f1.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="static/css/signup.css">
</head>
<body>
    <nav class="navbar">
        
        <div class="navbar_logo">
            <a href="#">Sumda</a>
        </div>
        <hr>
    </nav>

        
    <form method="POST">
    <div class="wrap">
        <div class="signup">
        <h2>Sign Up</h2>
            <div class="signup_name">
                <h4>Nickname</h4>
                <input type="nickname" placeholder="Nickname">
            </div>
            <div class="signup_id">
                <h4>E-mail</h4>
                <input type="email" placeholder="Email">
            </div>
            <div class="signup_pw">
                <h4>Password</h4>
                <input type="password" placeholder="Password">
            </div>
            <div class="submit">
                <button type="submit" value="submit">Submit</button>
            </div>
        </div>
    </div>
    </form>
</body>
</html>

sumda/templates/write.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <button onclick="onLocation()">위치 불러오기</button>
        <form action="{% url 'sumda:write' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="location" style="display: None">
                <h3><label for="location">위치정보</label></h3>
                <input class="location_input" name="location" type="text" value="" />
            </div>
            <br />
            <h3>제목</h3>
            <input type="text" name="title" />
            <br />

            <h3>닉네임</h3>
            <input type="text" name="nickname" />
            <br />
            <h3>일기쓰기</h3>
            <textarea name="content" cols="30" rows="10" placeholder="이쁜 일기 써보세요"></textarea>

            <button type="submit">작성하기</button>
        </form>
    </body>

    <script
        type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=46d5f6c310a78632612936d0ea60df74&libraries=services"
    ></script>
    <script></script>
    <script>
        function getLocation() {
            if (navigator.geolocation) {
                // GPS를 지원하면
                navigator.geolocation.getCurrentPosition(
                    function (position) {
                        const latitude = position.coords.latitude;
                        const longitude = position.coords.longitude;
                        const coords = position.coords;

                        var geocoder = new kakao.maps.services.Geocoder();
                        function searchAddrFromCoords(coords, callback) {
                            // 좌표로 행정동 주소 정보를 요청합니다
                            geocoder.coord2RegionCode(coords.longitude, coords.latitude, callback);
                        }
                        searchAddrFromCoords(coords, displayCenterInfo);

                        function displayCenterInfo(result, status) {
                            if (status === kakao.maps.services.Status.OK) {
                                for (var i = 0; i < result.length; i++) {
                                    // 행정동의 region_type 값은 'H' 이므로
                                    if (result[i].region_type === "H") {
                                        const address = result[0].region_2depth_name;
                                        console.log(latitude + " " + longitude + " " + address);
                                        const element = document.querySelector(`.location`);
                                        element.style.display = "block";
                                        const input = document.querySelector(`.location_input`);
                                        input.value = address;
                                        console.log(element);
                                        break;
                                    }
                                }
                            }
                        }
                    },
                    function (error) {
                        console.error(error);
                    },
                    {
                        enableHighAccuracy: false,
                        maximumAge: 0,
                        timeout: Infinity,
                    }
                );
            } else {
                alert("GPS를 지원하지 않습니다");
            }
        }
        const onLocation = () => {
            getLocation();
        };
    </script>
</html>